CREATE TABLE [dbo].[T_RC_PESSOA] (
    [CD_CODIGO]      INT            IDENTITY (1, 1) NOT NULL,
    [NM_NOME]        NVARCHAR (250) NOT NULL,
    [DS_EMAIL]       NVARCHAR (250) NOT NULL,
    [VL_SENHA]       NVARCHAR (250) NOT NULL,
    [TP_TIPO]        BIT            NOT NULL,
    [DS_LOGRADOURO]  NVARCHAR (250) NOT NULL,
    [DS_NUMERO]      NVARCHAR (50)  NOT NULL,
    [DS_COMPLEMENTO] NVARCHAR (250) NULL,
    [DS_CIDADE]      NVARCHAR (250) NOT NULL,
    [DS_ESTADO]      NVARCHAR (250) NOT NULL,
    [VL_CEP]         NVARCHAR (8)   NOT NULL,
    [VL_LATITUDE]    NVARCHAR (100) NULL,
    [VL_LONGITUDE]   NVARCHAR (100) NULL,
    CONSTRAINT [PK_T_RC_PESSOA] PRIMARY KEY CLUSTERED ([CD_CODIGO] ASC)
);

