CREATE TABLE [dbo].[T_RC_COLETA] (
    [CD_COLETA]             INT             IDENTITY (1, 1) NOT NULL,
    [CD_OBJETO]             INT             NOT NULL,
    [CD_PESSOA_SOLICITANTE] INT             NOT NULL,
    [CD_PESSOA_COLETOR]     INT             NULL,
    [VL_QUANTIDADE]         INT             NULL,
    [VL_PESO]               NUMERIC (18, 3) NULL,
    [DS_ENDERECO]           NVARCHAR (250)  NOT NULL,
    [VL_LATITUDE]           NVARCHAR (100)  NOT NULL,
    [VL_LONGITUDE]          NVARCHAR (100)  NOT NULL ,
    [CD_STATUS]             INT             NOT NULL,
    [DT_DATA_SOLICITADA]    DATETIME        NOT NULL,
    [DT_DATA_COLETADA]      DATETIME        NULL,
    CONSTRAINT [PK_T_RC_COLETA] PRIMARY KEY CLUSTERED ([CD_COLETA] ASC),
    CONSTRAINT [FK_T_RC_COLETA_T_RC_OBJETO] FOREIGN KEY ([CD_OBJETO]) REFERENCES [dbo].[T_RC_OBJETO] ([CD_CODIGO]),
    CONSTRAINT [FK_T_RC_COLETA_T_RC_PESSOA] FOREIGN KEY ([CD_PESSOA_SOLICITANTE]) REFERENCES [dbo].[T_RC_PESSOA] ([CD_CODIGO]),
    CONSTRAINT [FK_T_RC_COLETA_T_RC_PESSOA1] FOREIGN KEY ([CD_PESSOA_COLETOR]) REFERENCES [dbo].[T_RC_PESSOA] ([CD_CODIGO])
);

