CREATE TABLE [dbo].[T_RC_OBJETO] (
    [CD_CODIGO] INT            IDENTITY (1, 1) NOT NULL,
    [NM_NOME]   NVARCHAR (250) NOT NULL,
    CONSTRAINT [PK_T_RC_OBJETO] PRIMARY KEY CLUSTERED ([CD_CODIGO] ASC)
);

