CREATE TABLE [dbo].[T_RC_PESSOA] (
    [CD_CODIGO]      INT            IDENTITY (1, 1) NOT NULL,
    [NM_NOME]        NVARCHAR (250) NOT NULL,
    [DS_EMAIL]       NVARCHAR (250) NOT NULL,
    [VL_SENHA]       NVARCHAR (250) NOT NULL,
    CONSTRAINT [PK_T_RC_PESSOA] PRIMARY KEY CLUSTERED ([CD_CODIGO] ASC)
);

