CREATE TABLE [dbo].[T_RC_PESSOA_JURIDICA] (
    [CD_CODIGO]       INT            NOT NULL,
    [NM_RAZAO_SOCIAL] NVARCHAR (250) NOT NULL,
    [DT_ABERTURA]     DATE           NOT NULL,
    [VL_CNPJ]         NVARCHAR (14)  NOT NULL,
    CONSTRAINT [PK_T_RC_PESSOA_JURIDICA] PRIMARY KEY CLUSTERED ([CD_CODIGO] ASC),
    CONSTRAINT [FK_T_RC_PESSOA_JURIDICA_T_RC_PESSOA] FOREIGN KEY ([CD_CODIGO]) REFERENCES [dbo].[T_RC_PESSOA] ([CD_CODIGO])
);

