CREATE TABLE [dbo].[T_RC_PESSOA_FISICA] (
    [CD_PESSOA]     INT           NOT NULL,
    [VL_CPF]        NVARCHAR (11) NOT NULL,
    [DT_NASCIMENTO] DATE          NOT NULL,
    [GENERO]        CHAR (1)      NULL,
    CONSTRAINT [PK_T_RC_PESSOA_FISICA] PRIMARY KEY CLUSTERED ([CD_PESSOA] ASC),
    CONSTRAINT [FK_T_RC_PESSOA_FISICA_T_RC_PESSOA] FOREIGN KEY ([CD_PESSOA]) REFERENCES [dbo].[T_RC_PESSOA] ([CD_CODIGO])
);

